[workspace]
resolver = "3"
members = [
    "packages/fsrouter",
    "packages/fsrouter-macro",
    "examples/basic",
]

[workspace.package]
edition = "2024"
authors = ["Goodwill Mzumala <fisothemes@egmail.com>"]
license = "MIT"
repository = "https://github.com/fisothemes/dioxus-fsrouter"

[workspace.dependencies]
dioxus = { version = "0.7", features = [] }
dioxus-logger = "0.7"
dioxus-fsrouter = { path = "packages/fsrouter" }
dioxus-fsrouter-macro = { path = "packages/fsrouter-macro" }
inventory = "0.3"
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
thiserror = "2.0"
indexmap = "2.12"
