[workspace]
members = [
    "dioxus-fsrouter",
    "dioxus-fsrouter-macro",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Goodwill Mzumala <fisothemes@egmail.com>"]
license = "MIT"
repository = "https://github.com/fisothemes/dioxus-fsrouter"

[workspace.dependencies]
dioxus = "0.7"
dioxus-fsrouter = { path = "dioxus-fsrouter" }
dioxus-fsrouter-macro = { path = "dioxus-fsrouter-macro" }

# Proc macro dependencies
syn = { version = "2.0", features = ["full", "extra-traits", "visit"] }
quote = "1.0"
proc-macro2 = "1.0"
darling = "0.21"

# Runtime dependencies
linkme = "0.3"
regex = "1.10"
once_cell = "1.19"
